"""Modelo inicial y propiedades demo."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

revision = '001_inicial'; down_revision = None; branch_labels = None; depends_on = None
def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.create_table('usuarios', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('email',sa.String(180),unique=True,nullable=False),sa.Column('nombre',sa.String(120),nullable=False),sa.Column('activo',sa.Boolean,server_default='true',nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('clientes', sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('usuario_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('usuarios.id'),unique=True),sa.Column('documento',sa.String(30),unique=True,nullable=False),sa.Column('telefono',sa.String(30)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('categorias',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('nombre',sa.String(80),unique=True,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('productos',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('categoria_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('categorias.id'),nullable=False),sa.Column('nombre',sa.String(150),nullable=False),sa.Column('descripcion',sa.Text,nullable=False),sa.Column('ubicacion',sa.String(180),nullable=False),sa.Column('sku',sa.String(30),unique=True,nullable=False),sa.Column('precio',sa.Numeric(14,2),nullable=False),sa.Column('rentabilidad_estimada',sa.Numeric(5,2),nullable=False),sa.Column('imagen_url',sa.String(500),nullable=False),sa.Column('estado',sa.String(30),server_default='Disponible'),sa.Column('activo',sa.Boolean,server_default='true'),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.CheckConstraint('precio >= 0'),sa.CheckConstraint('rentabilidad_estimada >= 0'))
    for table, cols in [('carritos',[('usuario_id','usuarios')]),('detalles_carrito',[('carrito_id','carritos'),('producto_id','productos')]),('pedidos',[('cliente_id','clientes')]),('detalles_pedido',[('pedido_id','pedidos'),('producto_id','productos')])]:
        columns=[sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True)]+[sa.Column(c,postgresql.UUID(as_uuid=True),sa.ForeignKey(f'{t}.id'),nullable=False) for c,t in cols]+[sa.Column('cantidad',sa.Integer,server_default='1'),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now())]
        if table=='pedidos': columns += [sa.Column('estado',sa.String(30),server_default='Pendiente'),sa.Column('total',sa.Numeric(14,2),server_default='0')]
        if table=='detalles_pedido': columns += [sa.Column('precio_unitario',sa.Numeric(14,2),nullable=False)]
        op.create_table(table,*columns)
    categorias={name:uuid.uuid4() for name in ['Casas de lujo','Departamentos','Comercial','Preventa']}
    for name, ident in categorias.items(): op.execute(sa.text('INSERT INTO categorias (id,nombre) VALUES (:id,:name)').bindparams(id=ident,name=name))
    data=[('Casa Lumen','Arquitectura serena y espacios abiertos.','La Molina, Lima','NID-001',485000,8.4,'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=85','En oferta','Casas de lujo'),('Atelier 48','Departamento urbano con demanda sostenida.','Miraflores, Lima','NID-002',212000,7.8,'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85','Disponible','Departamentos'),('Patio Central','Local comercial en el corazón financiero.','San Isidro, Lima','NID-003',695000,10.2,'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=85','Disponible','Comercial'),('Brisa Norte','Proyecto residencial con entrega 2027.','Asia, Lima','NID-004',178000,9.1,'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1000&q=85','Reservada','Preventa')]
    for n,d,u,s,p,r,img,e,c in data: op.execute(sa.text('INSERT INTO productos (id,categoria_id,nombre,descripcion,ubicacion,sku,precio,rentabilidad_estimada,imagen_url,estado,activo) VALUES (:id,:cat,:n,:d,:u,:s,:p,:r,:img,:e,true)').bindparams(id=uuid.uuid4(),cat=categorias[c],n=n,d=d,u=u,s=s,p=p,r=r,img=img,e=e))
def downgrade() -> None:
    for table in ['detalles_pedido','pedidos','detalles_carrito','carritos','productos','categorias','clientes','usuarios']: op.drop_table(table)
